"""evidence image column

Revision ID: 093529326416
Revises: 8f553529a9db
Create Date: 2026-09-27 14:16:07.332085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093529326416'
down_revision: Union[str, Sequence[str], None] = '8f553529a9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_captures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_captures', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
