"""voice latency samples

Revision ID: 8f553529a9db
Revises: e1a8c0a8d201
Create Date: 2026-09-26 17:01:00.527957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f553529a9db'
down_revision: Union[str, Sequence[str], None] = 'e1a8c0a8d201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_latency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('first_audio_ms', sa.Integer(), nullable=False),
    sa.Column('turn_kind', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_latency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_latency_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_latency_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_latency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_latency_created_at'))
        batch_op.drop_index(batch_op.f('ix_voice_latency_claim_id'))

    op.drop_table('voice_latency')
    # ### end Alembic commands ###
