"""initial schema

Revision ID: e1a8c0a8d201
Revises: 
Create Date: 2026-09-25 19:16:05.831231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a8c0a8d201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pipeline_route', sa.String(length=32), nullable=True),
    sa.Column('frozen_route', sa.String(length=32), nullable=True),
    sa.Column('route_override', sa.String(length=32), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('claimant_name', sa.String(length=200), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('result_revision', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('escalations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_claim_id'), ['claim_id'], unique=False)

    op.create_table('evidence_captures',
    sa.Column('capture_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('claimant_claim', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('document_types', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    with op.batch_alter_table('evidence_captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_captures_claim_id'), ['claim_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_id'), ['rule_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_claim_id'), ['claim_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'turn_id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_claim_id'))

    op.drop_table('turns')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_claim_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_findings_claim_id'))

    op.drop_table('findings')
    with op.batch_alter_table('evidence_captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_captures_claim_id'))

    op.drop_table('evidence_captures')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_claim_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_updated_at'))
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_owner'))

    op.drop_table('claims')
    # ### end Alembic commands ###
